version: '2'

services:
  testaddin1:
    image: testaddin1:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "3001:3001"
      - "5858:5858"
    volumes:
      - .:/src
    environment:
      - REMOTE_DEBUGGING
